export const BUSINESS = {
  name: "The Patch Boys of Bergen County",
  phone: "(201) 555-0199",
  email: "bergen@thepatchboys.com",
  tagline: "Seamless Patches. Superior Service.™",
  description: "Bergen County's trusted drywall repair experts. Fast, professional drywall and ceiling repairs with free estimates and same-day service.",
  address: "Bergen County, NJ",
  hours: "Mon-Fri: 8AM-6PM | Sat: 9AM-3PM",
  googleMapsEmbed: "",
};

export const SERVICES = [
  {
    slug: "drywall-repair",
    title: "Drywall Repair",
    shortDesc: "Expert patching and repair for holes, cracks, dents, and water damage in your drywall.",
    longDesc: "Whether it's a small nail hole or a large gash from moving furniture, our skilled technicians restore your walls to their original condition. We handle all types of drywall damage including holes, cracks, water damage, and settling cracks with precision and care.",
    icon: "🔧",
    benefits: ["Same-day repairs available", "Invisible patch results", "All hole sizes handled", "Water damage specialists"],
    keywords: ["drywall repair", "drywall patching", "hole repair", "wall repair", "sheetrock repair"],
  },
  {
    slug: "ceiling-repair",
    title: "Ceiling Repair",
    shortDesc: "Fix cracks, water stains, sagging, and damage to restore your ceiling's appearance.",
    longDesc: "Ceiling damage can be caused by water leaks, settling, or age. Our team expertly repairs cracks, water stains, sagging sections, and other ceiling issues. We ensure a smooth, seamless finish that blends perfectly with your existing ceiling.",
    icon: "🏠",
    benefits: ["Water stain removal", "Crack and seam repair", "Sagging ceiling fix", "Seamless blending"],
    keywords: ["ceiling repair", "ceiling crack repair", "water stain ceiling", "ceiling patching"],
  },
  {
    slug: "plaster-repair",
    title: "Plaster Repair",
    shortDesc: "Specialized repair for older plaster walls and ceilings common in Bergen County homes.",
    longDesc: "Many Bergen County homes feature original plaster walls that require specialized repair techniques. Our technicians are trained in traditional plaster repair methods, preserving the character of your home while restoring damaged areas to their former beauty.",
    icon: "🏗️",
    benefits: ["Historic home specialists", "Traditional methods", "Crack and crumble repair", "Preserves home character"],
    keywords: ["plaster repair", "plaster wall repair", "plaster ceiling repair", "old house plaster"],
  },
  {
    slug: "drywall-installation",
    title: "Drywall Installation",
    shortDesc: "Professional new drywall installation for renovations, additions, and new construction.",
    longDesc: "Need new drywall hung? Whether you're finishing a basement, renovating a room, or building an addition, our team delivers precise drywall installation with clean cuts, tight seams, and professional finishing. We handle projects of all sizes throughout Bergen County.",
    icon: "📐",
    benefits: ["Basement finishing", "Room renovations", "Additions & new construction", "Professional finishing"],
    keywords: ["drywall installation", "drywall hanging", "sheetrock installation", "new drywall"],
  },
  {
    slug: "popcorn-ceiling-removal",
    title: "Popcorn Ceiling Removal",
    shortDesc: "Modernize your home by removing outdated popcorn texture from your ceilings.",
    longDesc: "Popcorn ceilings are outdated and can even contain asbestos in older homes. Our team safely removes popcorn ceiling texture and replaces it with a smooth, modern finish that instantly updates the look of any room and can increase your home's value.",
    icon: "✨",
    benefits: ["Safe removal process", "Modern smooth finish", "Increases home value", "Asbestos-aware procedures"],
    keywords: ["popcorn ceiling removal", "popcorn ceiling", "textured ceiling removal", "ceiling modernization"],
  },
  {
    slug: "texture-matching",
    title: "Texture Matching",
    shortDesc: "Seamless texture matching so your repairs are completely invisible.",
    longDesc: "The hallmark of a great drywall repair is invisible results. Our texture matching experts analyze your existing wall or ceiling texture and replicate it precisely, ensuring that repaired areas blend seamlessly with the surrounding surface. From orange peel to knockdown, we match it all.",
    icon: "🎨",
    benefits: ["Invisible repair results", "All texture types matched", "Orange peel & knockdown", "Expert color matching"],
    keywords: ["texture matching", "wall texture matching", "drywall texture", "knockdown texture", "orange peel texture"],
  },
  {
    slug: "painting",
    title: "Painting & Touch-Up",
    shortDesc: "Complete your repair with professional painting and color matching for a flawless finish.",
    longDesc: "Why hire two contractors when one can do it all? After repairing your drywall, we offer professional painting and touch-up services to complete the job from start to finish. Our color matching ensures a seamless blend with your existing paint.",
    icon: "🖌️",
    benefits: ["One contractor, complete job", "Expert color matching", "Interior touch-ups", "Full room painting available"],
    keywords: ["painting after drywall repair", "paint matching", "interior painting", "touch-up painting"],
  },
];

export const BERGEN_TOWNS = [
  { name: "Hackensack", slug: "hackensack", zip: "07601", population: "44,522" },
  { name: "Paramus", slug: "paramus", zip: "07652", population: "26,342" },
  { name: "Teaneck", slug: "teaneck", zip: "07666", population: "40,356" },
  { name: "Fort Lee", slug: "fort-lee", zip: "07024", population: "37,907" },
  { name: "Englewood", slug: "englewood", zip: "07631", population: "28,390" },
  { name: "Ridgewood", slug: "ridgewood", zip: "07450", population: "25,979" },
  { name: "Bergenfield", slug: "bergenfield", zip: "07621", population: "27,375" },
  { name: "Fair Lawn", slug: "fair-lawn", zip: "07410", population: "33,710" },
  { name: "Garfield", slug: "garfield", zip: "07026", population: "32,304" },
  { name: "Lodi", slug: "lodi", zip: "07644", population: "24,842" },
  { name: "Mahwah", slug: "mahwah", zip: "07430", population: "26,363" },
  { name: "Ramsey", slug: "ramsey", zip: "07446", population: "14,893" },
  { name: "Wyckoff", slug: "wyckoff", zip: "07481", population: "17,006" },
  { name: "Glen Rock", slug: "glen-rock", zip: "07452", population: "11,926" },
  { name: "Rutherford", slug: "rutherford", zip: "07070", population: "18,858" },
  { name: "Lyndhurst", slug: "lyndhurst", zip: "07071", population: "22,324" },
  { name: "Saddle Brook", slug: "saddle-brook", zip: "07663", population: "13,628" },
  { name: "River Edge", slug: "river-edge", zip: "07661", population: "11,688" },
  { name: "Closter", slug: "closter", zip: "07624", population: "8,731" },
  { name: "Westwood", slug: "westwood", zip: "07675", population: "11,325" },
  { name: "Dumont", slug: "dumont", zip: "07628", population: "18,140" },
  { name: "New Milford", slug: "new-milford", zip: "07646", population: "16,477" },
  { name: "Oradell", slug: "oradell", zip: "07649", population: "8,164" },
  { name: "Waldwick", slug: "waldwick", zip: "07463", population: "10,102" },
  { name: "Upper Saddle River", slug: "upper-saddle-river", zip: "07458", population: "8,208" },
  { name: "Allendale", slug: "allendale", zip: "07401", population: "6,848" },
  { name: "Cresskill", slug: "cresskill", zip: "07626", population: "9,069" },
  { name: "Demarest", slug: "demarest", zip: "07627", population: "4,985" },
  { name: "Emerson", slug: "emerson", zip: "07630", population: "7,768" },
  { name: "Hillsdale", slug: "hillsdale", zip: "07642", population: "10,219" },
  { name: "Montvale", slug: "montvale", zip: "07645", population: "8,632" },
  { name: "Park Ridge", slug: "park-ridge", zip: "07656", population: "9,019" },
  { name: "Washington Township", slug: "washington-township", zip: "07676", population: "9,721" },
  { name: "Woodcliff Lake", slug: "woodcliff-lake", zip: "07677", population: "5,998" },
  { name: "Haworth", slug: "haworth", zip: "07641", population: "3,509" },
  { name: "Old Tappan", slug: "old-tappan", zip: "07675", population: "5,983" },
  { name: "Northvale", slug: "northvale", zip: "07647", population: "4,861" },
  { name: "Norwood", slug: "norwood", zip: "07648", population: "5,793" },
];

export const TESTIMONIALS = [
  {
    name: "Michael R.",
    location: "Ridgewood, NJ",
    text: "Had a huge hole in the wall from a doorknob. The Patch Boys came out the same day, and you can't even tell where it was. Incredible work!",
    rating: 5,
  },
  {
    name: "Sarah T.",
    location: "Paramus, NJ",
    text: "We had water damage on our ceiling from a leak. They repaired it perfectly and matched the texture so well that even we can't find the patch. Highly recommend!",
    rating: 5,
  },
  {
    name: "David & Kim L.",
    location: "Teaneck, NJ",
    text: "Best drywall repair experience ever. On time, clean, professional, and the price was very fair. They fixed 6 holes in under 2 hours. Will definitely use again.",
    rating: 5,
  },
  {
    name: "Jennifer M.",
    location: "Fort Lee, NJ",
    text: "Had our popcorn ceiling removed in the living room. What a difference! The team was fast, clean, and the smooth ceiling looks amazing. Worth every penny.",
    rating: 5,
  },
  {
    name: "Robert A.",
    location: "Hackensack, NJ",
    text: "I called in the morning and they were at my house by the afternoon. Fixed the cracks in my plaster walls beautifully. Old house, new look. Thank you!",
    rating: 5,
  },
  {
    name: "Lisa P.",
    location: "Englewood, NJ",
    text: "We're renovating our home and needed drywall installed in the basement. Professional crew, clean work, and a perfect finish. Couldn't be happier!",
    rating: 5,
  },
];

export const FAQ = [
  {
    q: "How much does drywall repair cost?",
    a: "Most drywall repairs range from $150 to $500 depending on the size and complexity. We provide free, no-obligation estimates so you'll know the exact cost upfront before any work begins.",
  },
  {
    q: "Do you offer free estimates?",
    a: "Yes! We offer completely free, no-obligation estimates for all drywall repair and installation services throughout Bergen County. Call us or fill out our contact form to schedule yours.",
  },
  {
    q: "How long does a typical repair take?",
    a: "Most repairs are completed in just one visit, typically within 1-3 hours. Larger projects like popcorn ceiling removal or drywall installation may take longer, but we'll give you a clear timeline upfront.",
  },
  {
    q: "Do you match existing textures and paint?",
    a: "Absolutely! Texture matching is one of our specialties. We analyze your existing wall or ceiling texture and replicate it precisely so the repair is completely invisible.",
  },
  {
    q: "Are you licensed and insured?",
    a: "Yes, The Patch Boys is fully licensed and insured. We carry comprehensive liability insurance for your complete peace of mind.",
  },
  {
    q: "What areas in Bergen County do you serve?",
    a: "We serve all of Bergen County including Hackensack, Paramus, Teaneck, Fort Lee, Englewood, Ridgewood, Bergenfield, Fair Lawn, and all surrounding communities. If you're in Bergen County, we've got you covered!",
  },
  {
    q: "Can you fix water-damaged drywall?",
    a: "Yes, water damage repair is one of our core services. We remove the damaged section, treat for any moisture issues, install new drywall, and match the texture and paint for a seamless finish.",
  },
  {
    q: "Do I need to be home during the repair?",
    a: "We prefer that someone 18 or older be present during the repair. This allows us to discuss any findings and ensure you're completely satisfied with the work before we leave.",
  },
];
